### ISSUE TITLE
Windows Build

### ISSUE THREAD

**Issue by ax3l** [conda-forge/ccache-feedstock#27]
Hi @conda-forge/ccache maintainers,

I noticed that this feedstock does not yet build out Windows binaries. Should we add this?

**Comment by wolfv** [comment]
yes please! :) There were at least two attempts in the past (check PR's)

**Comment by wolfv** [comment]
I've started building it in #31 using plain MSVC 2019. works well!

**Comment by wolfv** [comment]
We have them, but afaik ccache doesn't (yet) support MSVC. GCC should work though :)
